import Layout from "@/features/layout/components/Layout";

import { CatalogProvider } from "@/contexts/CatalogContext";
import ProductList from "@/features/products/components/ProductList";
import SearchBox from "@/features/search/SearchBox";
import Head from "next/head";

export default function SmartphoneList() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CatalogProvider>
        <Layout>
          <SearchBox />
          <ProductList />
        </Layout>
      </CatalogProvider>
    </>
  );
}
